#!/bin/sh

ESCAPED_VITE_FIREBASE_SERVICE_CREDENTIALS=$(echo "$VITE_FIREBASE_SERVICE_CREDENTIALS" | sed 's/"/\\"/g')

cat <<EOF > /app/assets/config.json
{
    "VITE_API_URL": "$VITE_API_URL",
    "VITE_CHAT_HUB_URL": "$VITE_CHAT_HUB_URL",
    "VITE_FIREBASE_SERVICE_CREDENTIALS": "$ESCAPED_VITE_FIREBASE_SERVICE_CREDENTIALS"
}
EOF

exec "$@"